apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

images:
- name: goserver
  newName: renatofh/gitopsfc
  newTag: 5d76fd29552dd387a9f320ee7515cfb49424dff3
